name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync version with tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Syncing version to $VERSION"
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml

      - name: Build for linux
        run: cd build && ./build-release.sh

      - name: Package Linux
        run: |
          cd target/release
          zip -r ../../civiewer-linux-x64.zip civiewer ThirdPartyNotices.txt LICENSE

      - name: Build for Windows
        run: cd build && ./build-windows.sh

      - name: Package Windows
        run: |
          cd target/x86_64-pc-windows-gnu/release
          zip -r ../../../civiewer-windows-x64.zip . -i "*.exe" "*.dll" "ThirdPartyNotices.txt" "LICENSE"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            civiewer-linux-x64.zip
            civiewer-windows-x64.zip